
//INICIALIZANDO ARRAY CON VALORES
let numeros = [200, 150, 100, -50, 300];

for (let i = 0; i < numeros.Length; i++)
{
    console.log(numeros[i] * i);
}

//EXPLICANDO EL FOR
//EN LA PRIMERA ITERACION i VALE 0 Y EN CADA ITERACION AUMENTA EL VALOR EN 1.

//EN LA PRIMERA ITERACION numeros[0] = 200 QUE ES IGUAL AL VALOR DE LA POSICION 0 DEL ARRAY
//EN LA SEGUNDA ITERACION numeros[1] = 150 QUE ES IGUAL AL VALOR DE LA POSICION 1 DEL ARRAY
//EN LA TERCER ITERACION numeros[2] = 100 QUE ES IGUAL AL VALOR DE LA POSICION 2 DEL ARRAY
//EN LA CUARTA ITERACION numeros[3] = -50 QUE ES IGUAL AL VALOR DE LA POSICION 3 DEL ARRAY
//EN LA QUINTA ITERACION numeros[4] = 300 QUE ES IGUAL AL VALOR DE LA POSICION 4 DEL ARRAY

//AL MULTIPLICAR SE OBTIENE LO SIGUIENTE
// numeros[0] * 0 = 0
// numeros[1] * 1 = 150
// numeros[2] * 2 = 200
// numeros[3] * 3 = -150
// numeros[4] * 4 = 1200